### PR TITLE
Development environment with Nix

### PR DESCRIPTION
**Pull request by Ma27**
Just a work in progress, I'd like to figure out how to work with [Nix](https://nixos.org/nix/) works with the setup (and makes the development easier)

ToDO

- [x] Tests working
- [x] Simplify Redis test setup
- [x] Travis-CI with Nix
- [x] confirm that non-Nix setup is still usable

### CODE REVIEW

**Comment by Ma27** [comment]
for now: everything works fine locally, unfortunately a single test crashes on TravisCI repeatedly.
Currently trying to investigate what went wrong %)

**Comment by Ma27** [comment]
environment confusion on travis with Nix and Ubuntu, tests passing now locally and (should) work on travis

**Comment by Ma27** [comment]
@herzrasen could you please have a short look at this? :)

**Comment by Ma27** [comment]
merged for now, let's see if this will improve the setup :-)

**Review by herzrasen — COMMENTED** [review]
Sorry, I overlooked the request for review. Looks good to me, though I'm not a Nix expert.

**Comment by Ma27** [comment]
that should be fine, as long as you don't have problems now it should be fine :)

In case you're experiencing unexpected issues feel free to comment here, this was just to make it compatible wiht my own setup.

**Pull request merged**
