### PR TITLE
Update and refactor project build structure

### PR DESCRIPTION
**Pull request by Ma27**
SBT 1.x required several changes to be done to build properly
(see https://www.scala-sbt.org/1.0/docs/Migrating-from-sbt-013x.html).
The following changes have been applied:

- sbt.version: 0.13.15 -> 1.1.0
- crossScalaVersions[2.11.8 -> 2.11.11]
- the over-engineered `Build.scala` has been replaced with a
  light-weight `build.sbt`

Furthermore all plugins have been bumped to use their latest versions
with support for SBT 1.x.

The `scalameter` benchmarks were severely outdated and broke the build
after the update. Instead of `sbt-jmh` a simple configuration using an
additional testing framework has been added. It was needed to patch the
public API of the measurer and, furthermore the benchmark scripts were
moved into the testing directories to run everything using `sbt test`.

### CODE REVIEW

**Review by herzrasen — APPROVED** [review]
Looks much better now. Thanks!

**Comment by herzrasen** [comment]
I accidentally pushed my changes on Issue #5  into your branch.

**Comment by Ma27** [comment]
@herzrasen is it okay for you if I force-push this branch and you open a new branch with a separate PR (that should make the reviewing easier :))

**Comment by herzrasen** [comment]
@Ma27 yes, sure

**Comment by Ma27** [comment]
the build is still failing, I also think that it's not a great idea to run benchmarks during `sbt test` (as shown in the `scalameter` docs). Will implement a multi-build with two roots, then the benchmarks are entirely separated from the rest...

**Comment by herzrasen** [comment]
I also thought about removing the benchmarks from the original project

**Comment by Ma27** [comment]
@herzrasen created a multi-build now. Let's wait for the feedback of @kardapoltsev and then we could ship this :)

**Comment by Ma27** [comment]
@kardapoltsev anything to add from your side? If you're fine with this, I'd merge this tomorrow and ship a new release :)

**Pull request merged**
