### PR TITLE
scalacheck dependency should be only for Test

### PR DESCRIPTION
**Pull request by vshalts**
Hey,

can you please make scalacheck dependency Test only.  Currently, it became transitive dependency and cause conflicts (we use another version of scalacheck that is incompatible with this one)

Thanks!

### CODE REVIEW

**Comment by herzrasen** [comment]
Hi @vshalts, thanks for your PR. Seems like a reasonable request to me.

**Comment by Ma27** [comment]
good catch! Let's wait for the Travis CI to complete and merge then %)

**Comment by Ma27** [comment]
ah, missed @herzrasen's message :sweat_smile:

**Comment by herzrasen** [comment]
@vshalts @Ma27 just merged it back to master.

**Comment by Ma27** [comment]
seems reasonable, thanks!

**Comment by vshalts** [comment]
Guys,
great thanks for merge! I don't know how releases work. Is it possible to make it available in Maven too (1.8.4)? I will appreciate this!

**Comment by Ma27** [comment]
yeah, some months ago I set up a pipeline to build releases.
As there aren't any critical issues ATM, I'd create a release tonight. As soon as this is done, I'd ping you ok?

**Comment by vshalts** [comment]
yeah, that perfect! thanks!

**Comment by Ma27** [comment]
@vshalts here you go: https://search.maven.org/#artifactdetails%7Ccom.github.Ma27%7Crediscala_2.12%7C1.8.4%7Cjar :-)

**Comment by vshalts** [comment]
@Ma27 Cool! Thanks!!

**Comment by Ma27** [comment]
you're welcome! %)

**Comment by Ma27** [comment]
btw @herzrasen, as you're quite active, do you think that access to Maven Central to alter rediscala might be useful for you?

**Pull request merged**
